# frozen_string_literal: true

source "https://rubygems.org"

gem 'debug'
gem 'rspec'
gem 'guard'
gem 'guard-rspec'

gem 'activesupport'


gem 'dry-types'
gem 'dry-struct'

gem 'simplecov', require: false, group: :test